name: Build & Test
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Install Packages
              run: npm install
            - name: Build Files
              run: npm run build
            - name: Run Tests
              run: npm run test
